### ISSUE TITLE
Not redirecting to payment page

### ISSUE THREAD

**Issue by remcovb** [robuust/craft-commerce-pay#3]
Hey,
This is more of a question but i can't get the plugin to be working. For the shop i'm building i use this little form:
```
<form method="post">
      {{ csrfInput() }}
      {{ actionInput('commerce/payments/pay') }}
      {{ redirectInput('afrekenen/bestelling?number='~cart.number) }}
      {{ hiddenInput('cancelUrl', '/commerce/checkout/payment'|hash) }}
      <button>Pay Now</button>
    </form>
```
Its seem pretty straightforward but when I press submit, i keep staying on the same page instead of redirecting to the payment page. I tested the form with a Mollie api key which works perfect, so i can not really see the issue. Am i missing something?

My project versions:
PAY: v1.1.1
Craft commerce: v4.1.1
Craft: v4.2.3

**Comment by boboldehampsink** [comment]
Does the PAY payment log say anything? You might be wrongly authenticated or something

**Comment by chillibe** [comment]
It does have something to do with the authentication.
Is Token code the same as the Secret in the pay back office?
It is somewhat unclear what the token code is.
![image](https://user-images.githubusercontent.com/1632418/188626220-0edce4b0-e3da-4fed-9fab-f50f556756df.png)

**Comment by boboldehampsink** [comment]
In this page https://admin.pay.nl/company/tokens you will find a table where the first column is "Code" - which is the Token Code. The second column is Token wich is the API Token. Under Beheer - Verkooplocaties you will find a code which is the Service ID.

**Comment by chillibe** [comment]
OK, thanks for the clarification. Unfortunately, I still get the following error.

```
Client error: `POST https://rest-api.pay.nl/v12/transaction/getServicePaymentOptions/json` resulted in a `401 Unauthorized` response
↵
Caused by: Http\Client\Exception\HttpException
Client error: `POST https://rest-api.pay.nl/v12/transaction/getServicePaymentOptions/json` resulted in a `401 Unauthorized` response

```
Can I give you some more information about our setup?

**Comment by boboldehampsink** [comment]
Sure, you can mail me in private @ bob@robuust.digital
