### ISSUE TITLE
Share an other nr than the id as payment reference to pay.nl

### ISSUE THREAD

**Issue by jripmeester** [robuust/craft-commerce-pay#8]
Hi!

Our client wants to use the order reference nr in pay.nl to identify which payment is for which order. It now contains the order id.
Is there a way to share the reference to pay.nl instead of the id?

Thanks in advance!

John

**Comment by boboldehampsink** [comment]
Hi John,

Unfortunately, there isn't. This is because the order reference is only created AFTER payment - so we don't know it when we submit to PAY.
