### ISSUE TITLE
Pay.nl krijgt 500 status ondanks succesvolle betaling

### ISSUE THREAD

**Issue by jripmeester** [robuust/craft-commerce-pay#9]
Het betaalproces van de webshop werkt als een zonnetje maar pay.nl blijft mails sturen dat de betalingen mislukken (terwijl ze wel gewoon slagen). Dit blijkt te komen omdat Craft een 500 error terugstuurt. Als ik in de pay.nl logs kijk dan zie ik inderdaad wat geks in de exchange url maar weet niet of dit het is.

Hebben jullie dit gedrag eerder gehoord en zou ik misschien de exchange url mogen delen dat jullie er eens een kijkje naar nemen?

Thanks alvast!

**Comment by boboldehampsink** [comment]
Hi @jripmeester - welke Craft versie en plugin versie gebruik je? Dit is al wel eens voorgekomen en gefixed in 1.1.3

**Comment by jripmeester** [comment]
De site gebruikt:
Craft 4.5.12
Commerce 4.3.3
PAY for Craft Commerce 1.1.4

**Comment by boboldehampsink** [comment]
Kun je in je eigen logs zien wat de 500 precies is?

**Comment by jripmeester** [comment]
Ik zie deze error op de webhooks terug komen:

2024-01-30 01:23:17 [web.ERROR] [commerce] Exception while processing webhook: The transactionReference parameter is required Exception thrown in /projects/soundflex_9c/releases/fd7d4fe1e099893dcd5d57be2a9fb91594671ed9/vendor/omnipay/common/src/Common/ParametersTrait.php:81 Stack trace: 
#0 /projects/soundflex_9c/releases/fd7d4fe1e099893dcd5d57be2a9fb91594671ed9/vendor/paynl/omnipay-paynl/src/Message/Request/FetchTransactionRequest.php(22): Omnipay\Common\Message\AbstractRequest->validate() 
#1 /projects/soundflex_9c/releases/fd7d4fe1e099893dcd5d57be2a9fb91594671ed9/vendor/omnipay/common/src/Common/Message/AbstractRequest.php(686): Omnipay\Paynl\Message\Request\FetchTransactionRequest->getData() 
#2 /projects/soundflex_9c/releases/fd7d4fe1e099893dcd5d57be2a9fb91594671ed9/vendor/robuust/craft-commerce-pay/src/gateways/Gateway.php(216): Omnipay\Common\Message\AbstractRequest->send() 
#3 /projects/soundflex_9c/releases/fd7d4fe1e099893dcd5d57be2a9fb91594671ed9/vendor/craftcms/commerce/src/services/Webhooks.php(97): robuust\pay\gateways\Gateway->processWebHook() 
#4 /projects/soundflex_9c/releases/fd7d4fe1e099893dcd5d57be2a9fb91594671ed9/vendor/craftcms/commerce/src/controllers/WebhooksController.php(55): craft\commerce\services\Webhooks->processWebhook() 
#5 [internal function]: craft\commerce\controllers\WebhooksController->actionProcessWebhook() 
#6 /projects/soundflex_9c/releases/fd7d4fe1e099893dcd5d57be2a9fb91594671ed9/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array() 
#7 /projects/soundflex_9c/releases/fd7d4fe1e099893dcd5d57be2a9fb91594671ed9/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams() 
#8 /projects/soundflex_9c/releases/fd7d4fe1e099893dcd5d57be2a9fb91594671ed9/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction() 
#9 /projects/soundflex_9c/releases/fd7d4fe1e099893dcd5d57be2a9fb91594671ed9/vendor/craftcms/cms/src/web/Application.php(305): yii\base\Module->runAction() 
#10 /projects/soundflex_9c/releases/fd7d4fe1e099893dcd5d57be2a9fb91594671ed9/vendor/craftcms/cms/src/web/Application.php(606): craft\web\Application->runAction() 
#11 /projects/soundflex_9c/releases/fd7d4fe1e099893dcd5d57be2a9fb91594671ed9/vendor/craftcms/cms/src/web/Application.php(284): craft\web\Application->_processActionRequest() 
#12 /projects/soundflex_9c/releases/fd7d4fe1e099893dcd5d57be2a9fb91594671ed9/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest() 
#13 /projects/soundflex_9c/releases/fd7d4fe1e099893dcd5d57be2a9fb91594671ed9/public_html/index.php(12): yii\base\Application->run() 
#14 {main} {"memory":11942080} 

En dit is de url:
https://www.sounds-venlo.nl/index.php?p=actions/commerce/webhooks/process-webhook&gateway=2&commerceTransactionHash=0f14ba2ef464270d21981085bbb42824?p=actions/commerce/webhooks/process-webhook&gateway=2&commerceTransactionHash=0f14ba2ef464270d21981085bbb42824&action=new_ppt&pincode=3*********&website_location_id=1&website_id=2&program_id=138843&promotor_id=0&tool=&info=&domain_id=&object=PAY+for+Craft+Commerce&ip_address=178.**.***.194&amount=33.5&extra1=&extra2=&extra3=&secret****18457&enduser_id=0&payment_session_id=2339248374&payment_profile_id=138&product_id=2162667&payment_method_id=4&starttime=2024-01-29+15%3A22%3A45&stoptime=2024-01-29+15%3A23%3A25&customer_id=wil*****randw***@***il.com&order_id=23*****74Xcb29a&customer_key=c228d12694***************3e33&country_id=12&country_code=NL

**Comment by boboldehampsink** [comment]
Try the newly released 1.1.5, which should fix this.
